// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var text = Props.text;
  var className = Props.className;
  var clickHandler = Props.clickHandler;
  return React.createElement("button", {
              className: className,
              onClick: clickHandler
            }, text);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
