// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";
import * as Button from "./Button.bs.js";

function DeletePostView(Props) {
  var post = Props.post;
  var restoreHandler = Props.restoreHandler;
  var deleteHandler = Props.deleteHandler;
  return React.createElement("div", {
              className: "relative bg-yellow-100 px-8 py-4 mb-6 h-40 rounded-md"
            }, React.createElement("p", {
                  className: "text-center white mb-1"
                }, "This post from " + Post.title(post) + " by " + Post.author(post) + " will be permanently removed in 10 seconds."), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement(Button.make, {
                      text: "Restore",
                      className: "mr-4 mt-4 bg-yellow-500 hover:bg-yellow-900 text-white py-2 px-4",
                      clickHandler: restoreHandler
                    }), React.createElement(Button.make, {
                      text: "Delete Immediately",
                      className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4",
                      clickHandler: deleteHandler
                    })), React.createElement("div", {
                  className: "bg-red-500 h-2 w-full absolute bottom-0 left-0 progress"
                }));
}

var make = DeletePostView;

export {
  make ,
  
}
/* Post Not a pure module */
