// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as PostView from "./PostView.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";
import * as DeletePostView from "./DeletePostView.bs.js";

function s(prim) {
  return prim;
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* DeleteLater */0 :
        return {
                posts: state.posts,
                forDeletion: Belt_MapString.set(state.forDeletion, Post.id(action._0), action._1)
              };
    case /* DeleteAbort */1 :
        return {
                posts: state.posts,
                forDeletion: Belt_MapString.remove(state.forDeletion, Post.id(action._0))
              };
    case /* DeleteNow */2 :
        var post = action._0;
        return {
                posts: state.posts.filter(function (x) {
                      return Post.id(x) !== Post.id(post);
                    }),
                forDeletion: Belt_MapString.remove(state.forDeletion, Post.id(post))
              };
    
  }
}

var initialState = {
  posts: Post.examples,
  forDeletion: undefined
};

function PostFeed(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var $$clearTimeout$1 = function (post) {
    var timeoutId = Belt_MapString.get(state.forDeletion, Post.id(post));
    if (timeoutId !== undefined) {
      clearTimeout(Caml_option.valFromOption(timeoutId));
    } else {
      console.log("ERROR: Unable to clear timeout");
    }
    
  };
  var posts = Belt_Array.map(state.posts, (function (post) {
          if (Belt_MapString.has(state.forDeletion, Post.id(post))) {
            var restoreHandler = function (_mouseEvent) {
              $$clearTimeout$1(post);
              return Curry._1(dispatch, {
                          TAG: /* DeleteAbort */1,
                          _0: post
                        });
            };
            var deleteHandler = function (_mouseEvent) {
              $$clearTimeout$1(post);
              return Curry._1(dispatch, {
                          TAG: /* DeleteNow */2,
                          _0: post
                        });
            };
            return React.createElement(DeletePostView.make, {
                        post: post,
                        restoreHandler: restoreHandler,
                        deleteHandler: deleteHandler,
                        key: Post.id(post)
                      });
          }
          var removeHandler = function (_mouseEvent) {
            return Curry._1(dispatch, {
                        TAG: /* DeleteLater */0,
                        _0: post,
                        _1: setTimeout((function (param) {
                                return Curry._1(dispatch, {
                                            TAG: /* DeleteNow */2,
                                            _0: post
                                          });
                              }), 10000)
                      });
          };
          return React.createElement(PostView.make, {
                      post: post,
                      removeHandler: removeHandler,
                      key: Post.id(post)
                    });
        }));
  return React.createElement("div", {
              className: "max-w-3xl mt-10 mx-auto"
            }, posts);
}

var make = PostFeed;

export {
  s ,
  reducer ,
  initialState ,
  make ,
  
}
/* Post Not a pure module */
