// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";
import * as Button from "./Button.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function createId(id, index) {
  return id + String(index);
}

function PostView(Props) {
  var post = Props.post;
  var removeHandler = Props.removeHandler;
  var paras = Belt_Array.mapWithIndex(Post.text(post), (function (index, para) {
          var id = Post.id(post);
          return React.createElement("p", {
                      key: id + String(index),
                      className: "mb-1 text-sm"
                    }, para);
        }));
  return React.createElement("div", {
              className: "bg-green-700 hover:bg-green-900 text-gray-300 hover:text-gray-100 px-8 py-4 mb-6"
            }, React.createElement("h2", {
                  className: "text-2xl mb-1"
                }, Post.title(post)), React.createElement("h3", {
                  className: "mb-4"
                }, Post.author(post)), paras, React.createElement(Button.make, {
                  text: "Remove this post",
                  className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4",
                  clickHandler: removeHandler
                }));
}

var make = PostView;

export {
  s ,
  createId ,
  make ,
  
}
/* Post Not a pure module */
